server:
  port: 8082
spring:
  application:
    name: contract-service
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/renthouses_contracts}
services:
  notification:
    url: ${NOTIFICATION_SERVICE_URL:http://localhost:8084}
  billing:
    url: ${BILLING_SERVICE_URL:http://localhost:8083}
management:
  endpoints:
    web:
      exposure:
        include: health,info
